### ISSUE TITLE
Tab characters cause misaligned overview in ec2 ls

### ISSUE THREAD

**Issue by svisser** [achiku/jungle#12]
When machine names have varying lengths the use of tab characters causes the columns not to be aligned properly (iTerm2, Mac OS X). I think this command should work out the maximum machine name length and pad all names with spaces, e.g.:

```python
>>> '{:<10}'.format('name')
'name      '
```

**Comment by achiku** [comment]
@svisser Thanks for the comment! I'll look into it this weekend.

**Comment by achiku** [comment]
@svisser Actually that's expected behavior. I wanted values separated by tab since values can be easily parsed after they are piped to the next command. However, it will be really useful if we can specify options to align values when ```jungle ec2 ls```.

**Comment by svisser** [comment]
@achiku shouldn't it be the other way around: that the default is a human-readable nicely aligned output and that a flag should be passed if the output should be parseable or piped into something else?

**Comment by achiku** [comment]
@svisser I personally don't think so, since output of ```ls``` is just plane space separated file names, and ```ls -l``` is more human-readable, detailed output. 

CLI library called hotdog https://github.com/yyuu/hotdog , will be really nice example.

**Comment by achiku** [comment]
@svisser I released the latest version and you should be able to list instance info aligned if you execute ```jungle ec2 ls -l```.

**Comment by svisser** [comment]
@achiku thanks for this change, much appreciated. I can confirm it works!
