### ISSUE TITLE
wildcards in command will glob with local filesystem and interfere with 'ls' operation

### ISSUE THREAD

**Issue by jolexa** [achiku/jungle#14]
Hi,

I found that when I'm trying to run `jungle ec2 ls *wildcard*` - it won't work if there is files in CWD that match.

Error: Got unexpected extra arguments

**Comment by ctrlrsf** [comment]
That's due to your shell (most likely bash) performing globbing / file expansion. Try putting any strings with * in single quotes such as `jungle ec2 ls '*wildcard*'`.

For more details see: http://www.tldp.org/LDP/abs/html/globbingref.html

**Comment by jolexa** [comment]
Yup, I'm aware of shell globbing. Just trying to follow the readme, as written. ;) Feel free to close this issue if desired.

**Comment by achiku** [comment]
@jolexa @ctrlrsf Thank you all :+1:  This is actually first time I see a problem was happened and solved without doing anything even though it's my repository :)
