### ISSUE TITLE
Output is not forlatted

### ISSUE THREAD

**Issue by andrewmclagan** [achiku/jungle#17]
for example `jungle ec2 ls` columns are not aligned properly

<img width="844" alt="screen shot 2015-09-04 at 11 56 56 am" src="https://cloud.githubusercontent.com/assets/1073259/9675084/4ef83958-52fc-11e5-9bd3-6f585db2b1a0.png">

**Comment by achiku** [comment]
@andrewmclagan I released the latest version and you should be able to list instance info aligned if you execute ```jungle ec2 ls -l```.

**Comment by andrewmclagan** [comment]
awesome!

**Comment by andrewmclagan** [comment]
Still, on version 0.1.3 this behavior is unformatted :-)

**Comment by achiku** [comment]
@andrewmclagan 

Could you try this? I think you didn't put ```-l``` option. 
```
 jungle ec2 ls -l
```

**Comment by andrewmclagan** [comment]
ding!
