### ISSUE TITLE
automatically enable bash completion

### ISSUE THREAD

**Issue by boyvinall** [achiku/jungle#62]
Looks like click handles bash completion for you - see http://click.pocoo.org/5/bashcomplete/.  You can enable this by running the following command:

    _JUNGLE_COMPLETE=source jungle > /etc/bash_completion.d/jungle

Would be nice to do this automatically when installed via pip.

**Comment by achiku** [comment]
@boyvinall This is great! It could produce problems if it automatically writes completion def to `/etc/bash_completion.d/jungle`, since user has to be a root when it installs jungle, but I will definitely add this to the README!!

**Comment by achiku** [comment]
Added! https://github.com/achiku/jungle#autocompletion-currently-only-supports-bash
